#!/usr/bin/env bash
set -euo pipefail

usage() {
    echo "Usage: $0 LABEL INSTALL_DIR [COMPATDATA_DIR]" >&2
    echo "Set ISAC_CAPTURE_BACKEND=1 to enable a narrow Division packet capture." >&2
    echo "Set ISAC_CAPTURE_BACKEND_FILTER=backend, tctd-pc, or startup (default: backend)." >&2
    exit 2
}

if [[ $# -lt 2 || $# -gt 3 ]]; then
    usage
fi

label=$1
install_dir=$2
compatdata_dir=${3:-}
capture_backend=${ISAC_CAPTURE_BACKEND:-0}
capture_backend_filter=${ISAC_CAPTURE_BACKEND_FILTER:-backend}
capture_action_markers=${ISAC_ACTION_MARKERS:-0}
capture_routes=${ISAC_ROUTE_AUDIT:-0}
capture_protection=${ISAC_SDK_PROTECT_TRACE:-0}

if [[ $capture_backend != 0 && $capture_backend != 1 ]]; then
    echo "ISAC_CAPTURE_BACKEND must be 0 or 1." >&2
    exit 2
fi

case $capture_backend_filter in
    backend)
        backend_bpf='tcp and (port 51000 or port 55000 or port 55002)'
        backend_pcap_name=backend-ports.pcap
        ;;
    tctd-pc)
        backend_bpf='tcp port 27015'
        backend_pcap_name=tctd-pc-27015.pcap
        ;;
    startup)
        backend_bpf='tcp and (port 27015 or port 51000 or port 55001 or port 55002)'
        backend_pcap_name=startup-ports.pcap
        ;;
    *)
        echo "ISAC_CAPTURE_BACKEND_FILTER must be backend, tctd-pc, or startup." >&2
        exit 2
        ;;
esac

if [[ $capture_action_markers != 0 && $capture_action_markers != 1 ]]; then
    echo "ISAC_ACTION_MARKERS must be 0 or 1." >&2
    exit 2
fi
if [[ $capture_routes != 0 && $capture_routes != 1 ]]; then
    echo "ISAC_ROUTE_AUDIT must be 0 or 1." >&2
    exit 2
fi
if [[ $capture_routes == 1 && -z $compatdata_dir ]]; then
    echo "Route audit requires a compatdata directory for prefix attribution." >&2
    exit 2
fi
if [[ $capture_protection != 0 && $capture_protection != 1 ]]; then
    echo "ISAC_SDK_PROTECT_TRACE must be 0 or 1." >&2
    exit 2
fi
if [[ $capture_protection == 1 && -z $compatdata_dir ]]; then
    echo "SDK mapping observer requires a compatdata directory." >&2
    exit 2
fi

if [[ $capture_backend == 1 ]] && ! command -v tcpdump >/dev/null 2>&1; then
    echo "Backend capture requested, but tcpdump is not installed." >&2
    exit 1
fi

if [[ ! $label =~ ^[a-zA-Z0-9_-]+$ ]]; then
    echo "Label may contain only letters, numbers, underscores, and hyphens." >&2
    exit 2
fi

if [[ ! -d $install_dir ]]; then
    echo "Install directory does not exist: $install_dir" >&2
    exit 2
fi

if [[ -n $compatdata_dir && ! -d $compatdata_dir ]]; then
    echo "Compatdata directory does not exist: $compatdata_dir" >&2
    exit 2
fi

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
project_dir=$(cd -- "$script_dir/.." && pwd)
install_dir=$(realpath -- "$install_dir")
if [[ -n $compatdata_dir ]]; then
    compatdata_dir=$(realpath -- "$compatdata_dir")
fi

started_at=$(date --iso-8601=seconds)
stamp=$(date +%Y%m%d-%H%M%S)
output_dir="$project_dir/evidence/$stamp-$label-linux"
proton_log_dir="$project_dir/evidence/proton-logs"
mkdir -p -- "$output_dir" "$proton_log_dir"
marker="$output_dir/.capture-started"
touch -- "$marker"
action_markers_file="$output_dir/action-markers.tsv"
if [[ $capture_action_markers == 1 ]]; then
    printf 'label\tobserved_at\tprobe_tick_ms\tworld_delta_ms\n' \
        > "$action_markers_file"
fi

# The forwarding probe appends to one persistent log in the game directory.
# Remember its starting size so this evidence folder receives only records
# generated by the current launch attempt.
probe_log="$install_dir/project-isac-uplay-probe.log"
probe_log_start_size=0
if [[ -f $probe_log ]]; then
    probe_log_start_size=$(stat -c '%s' -- "$probe_log")
fi

local_uplay_log="$install_dir/project-isac-uplay-local.log"
local_uplay_log_start_size=0
if [[ -f $local_uplay_log ]]; then
    local_uplay_log_start_size=$(stat -c '%s' -- "$local_uplay_log")
fi

# The optional address-only stack probe has its own persistent log. Track it
# independently so each evidence directory contains only this run's records.
stack_probe_log="$install_dir/project-isac-stack-probe.log"
stack_probe_log_start_size=0
if [[ -f $stack_probe_log ]]; then
    stack_probe_log_start_size=$(stat -c '%s' -- "$stack_probe_log")
fi

code_probe_log="$install_dir/project-isac-code-probe.log"
code_probe_log_start_size=0
if [[ -f $code_probe_log ]]; then
    code_probe_log_start_size=$(stat -c '%s' -- "$code_probe_log")
fi

dispatch_probe_log="$install_dir/project-isac-dispatch-probe.log"
dispatch_probe_log_start_size=0
if [[ -f $dispatch_probe_log ]]; then
    dispatch_probe_log_start_size=$(stat -c '%s' -- "$dispatch_probe_log")
fi

plaintext_probe_log="$install_dir/project-isac-plaintext-probe.log"
plaintext_probe_log_start_size=0
if [[ -f $plaintext_probe_log ]]; then
    plaintext_probe_log_start_size=$(stat -c '%s' -- "$plaintext_probe_log")
fi

uplay_abi_probe_log="$install_dir/project-isac-uplay-abi-probe.log"
uplay_abi_probe_log_start_size=0
if [[ -f $uplay_abi_probe_log ]]; then
    uplay_abi_probe_log_start_size=$(stat -c '%s' -- "$uplay_abi_probe_log")
fi

# A targeted type-0x0003 payload capture is intentionally kept out of the
# evidence bundle. Track only whether it existed, and restrict its mode after
# the launch attempt; never copy, hash, size, or print its contents here.
private_type3_capture="$install_dir/project-isac-type0003-private.bin"
private_type3_capture_existed=0
if [[ -f $private_type3_capture ]]; then
    private_type3_capture_existed=1
fi

# The post-Continue world-session request can contain account or session
# material. Treat it like the private type-0x0003 capture: record only file
# presence in the evidence summary and never copy, hash, size, or print it.
private_world_request="$install_dir/project-isac-world-request-private.bin"
private_world_request_existed=0
if [[ -f $private_world_request ]]; then
    private_world_request_existed=1
fi

# The timed reader-12 bootstrap stream is a replay artifact and may contain
# account, character, or world-session data. Keep it private exactly like the
# request capture and record only its presence in ordinary evidence.
private_world_snapshot="$install_dir/project-isac-world-bootstrap-private.bin"
private_world_snapshot_existed=0
if [[ -f $private_world_snapshot ]]; then
    private_world_snapshot_existed=1
fi

capture_process_list() {
    if [[ -n ${ISAC_HOST_PROC:-} ]]; then
        python3 "$script_dir/capture-process-list.py"
    else
        ps -eo pid=,ppid=,lstart=,comm=
    fi
}

snapshot_processes() {
    local stage=$1
    {
        echo "PID PPID STARTED COMMAND"
        capture_process_list |
            awk 'BEGIN { IGNORECASE=1 }
                 $NF ~ /(division|ubisoft|uplay|upc|wine|proton)/ { print }'
    } > "$output_dir/processes-$stage.txt"
}

snapshot_connections() {
    local stage=$1
    if command -v ss >/dev/null 2>&1; then
        {
            echo "Only sockets attributed to relevant visible processes are included."
            ss -H -tupn 2>/dev/null |
                awk 'BEGIN { IGNORECASE=1 }
                     /(division|ubisoft|uplay|upc|wine|proton)/ { print }'
        } > "$output_dir/connections-$stage.txt"
    else
        echo "The ss command is unavailable." > "$output_dir/connections-$stage.txt"
    fi
}

capture_timeline() {
    while true; do
        printf '\n=== %s ===\n' "$(date '+%Y-%m-%dT%H:%M:%S.%3N%:z')"
        capture_process_list |
            awk 'BEGIN { IGNORECASE=1 }
                 $NF ~ /(division|ubisoft|uplay|upc|wine|proton)/ { print }'
        if command -v ss >/dev/null 2>&1; then
            ss -H -tupn 2>/dev/null |
                awk 'BEGIN { IGNORECASE=1 }
                     /(division|ubisoft|uplay|upc|wine|proton)/ { print }'
        fi
        sleep 0.5
    done
}

stop_timeline() {
    if [[ -n ${timeline_pid:-} ]]; then
        kill "$timeline_pid" 2>/dev/null || true
        wait "$timeline_pid" 2>/dev/null || true
        timeline_pid=''
    fi
}

stop_backend_capture() {
    if [[ -n ${backend_capture_pid:-} ]]; then
        kill -INT "$backend_capture_pid" 2>/dev/null || true
        wait "$backend_capture_pid" 2>/dev/null || true
        backend_capture_pid=''
    fi
}

stop_capture_helpers() {
    stop_timeline
    stop_backend_capture
    stop_route_audit
    stop_protection_watch
}

stop_protection_watch() {
    if [[ -n ${protection_watch_pid:-} ]]; then
        kill -TERM "$protection_watch_pid" 2>/dev/null || true
        wait "$protection_watch_pid" 2>/dev/null || true
        protection_watch_pid=''
    fi
}

stop_route_audit() {
    if [[ -n ${route_audit_pid:-} ]]; then
        kill -TERM "$route_audit_pid" 2>/dev/null || true
        wait "$route_audit_pid" 2>/dev/null || true
        route_audit_pid=''
    fi
}

record_action_marker() {
    local action_label=$1
    local marker_tick=-
    local request_tick=-
    local world_delta=-

    if [[ -f $dispatch_probe_log ]]; then
        read -r marker_tick request_tick < <(
            tail -c "+$((dispatch_probe_log_start_size + 1))" \
                -- "$dispatch_probe_log" 2>/dev/null |
                awk '
                    match($0, /tick_ms=[0-9]+/) {
                        tick = substr($0, RSTART + 8, RLENGTH - 8)
                        latest = tick
                        if ($1 == "WORLD_REQUEST_MATCHED") {
                            request = tick
                        }
                    }
                    END {
                        print (latest == "" ? "-" : latest),
                            (request == "" ? "-" : request)
                    }
                '
        )
    fi
    if [[ $marker_tick =~ ^[0-9]+$ && $request_tick =~ ^[0-9]+$ ]]; then
        world_delta=$((marker_tick - request_tick))
    fi
    printf '%s\t%s\t%s\t%s\n' \
        "$action_label" \
        "$(date --iso-8601=ns)" \
        "$marker_tick" \
        "$world_delta" \
        >> "$action_markers_file"
    echo "Recorded marker: $action_label (world delta: ${world_delta} ms)" >&2
}

snapshot_processes before
snapshot_connections before

capture_timeline > "$output_dir/timeline.txt" &
timeline_pid=$!
backend_capture_pid=''
route_audit_pid=''
protection_watch_pid=''
backend_pcap="$output_dir/$backend_pcap_name"
backend_capture_log="$output_dir/tcpdump.log"
trap stop_capture_helpers EXIT INT TERM

if [[ $capture_routes == 1 ]]; then
    python3 "$script_dir/audit-game-routes.py" --prefix "$compatdata_dir/pfx" \
        --output-dir "$output_dir" 2> "$output_dir/route-audit-errors.log" &
    route_audit_pid=$!
    route_audit_ready=0
    for _ in {1..50}; do
        if grep -q '"event": "ready"' "$output_dir/route-audit.jsonl" 2>/dev/null; then
            route_audit_ready=1
            break
        fi
        if ! kill -0 "$route_audit_pid" 2>/dev/null; then break; fi
        sleep 0.1
    done
    if (( route_audit_ready == 0 )); then
        echo "WARNING: Route audit did not start; see route-audit-errors.log. Capture will continue." >&2
    fi
fi

if [[ $capture_protection == 1 ]]; then
    python3 "$script_dir/watch-sdk-protection.py" --prefix "$compatdata_dir/pfx" \
        --stack-log "$stack_probe_log" --offset "$stack_probe_log_start_size" \
        --output "$output_dir/sdk-protection-maps.jsonl" 2> "$output_dir/sdk-protection-maps-errors.log" &
    protection_watch_pid=$!
    protection_watch_ready=0
    for _ in {1..50}; do
        if grep -q '"event": "ready"' "$output_dir/sdk-protection-maps.jsonl" 2>/dev/null; then
            protection_watch_ready=1
            break
        fi
        if ! kill -0 "$protection_watch_pid" 2>/dev/null; then break; fi
        sleep 0.1
    done
    if (( protection_watch_ready == 0 )); then
        echo "WARNING: SDK mapping observer did not start; inspect sdk-protection-maps-errors.log." >&2
    fi
fi

find "$install_dir" -type f \( -iname '*.exe' -o -iname '*.dll' \) -print0 |
    sort -z |
    while IFS= read -r -d '' file; do
        relative=${file#"$install_dir"/}
        hash=$(sha256sum -- "$file" | awk '{print $1}')
        size=$(stat -c '%s' -- "$file")
        printf '%s  %s  %s\n' "$hash" "$size" "$relative"
    done > "$output_dir/executables.sha256"

if [[ $capture_backend == 1 ]]; then
    echo "Backend packet capture needs temporary raw-socket permission." >&2
    sudo -v
    capture_user=$(id -un)
    sudo tcpdump \
        -i any \
        -nn \
        -s 0 \
        -U \
        -B 4096 \
        -Z "$capture_user" \
        -w "$backend_pcap" \
        "$backend_bpf" \
        >/dev/null 2>"$backend_capture_log" &
    backend_capture_pid=$!
    sleep 0.5
    if ! kill -0 "$backend_capture_pid" 2>/dev/null; then
        wait "$backend_capture_pid" 2>/dev/null || true
        echo "tcpdump failed to start:" >&2
        sed -n '1,80p' "$backend_capture_log" >&2
        exit 1
    fi
fi

{
    echo "Capture directory: $output_dir"
    echo "Expected Proton log directory: $proton_log_dir"
    echo "Launch the game through Steam now."
    echo "Stop at a stable menu or the first stable error."
} >&2
if [[ $capture_action_markers == 1 ]]; then
    {
        echo "Action-marker mode is enabled."
        echo "After each action, return here and enter a short label."
        echo "Use begin_NAME/end_NAME pairs when you need a precise window."
        echo "Exit the game cleanly, then submit an empty label to finish."
    } >&2
    while true; do
        action_label=''
        if ! read -r -p "Marker label (empty finishes capture): " action_label; then
            break
        fi
        if [[ -z $action_label ]]; then
            break
        fi
        if [[ ! $action_label =~ ^[a-zA-Z0-9_-]+$ ]]; then
            echo "Marker labels may contain only letters, numbers, underscores, and hyphens." >&2
            continue
        fi
        record_action_marker "$action_label"
    done
else
    read -r -p "Press Enter when the launch attempt is finished: " _
fi

private_type3_capture_present=0
if [[ -f $private_type3_capture ]]; then
    chmod 600 -- "$private_type3_capture"
    private_type3_capture_present=1
fi

private_world_request_present=0
if [[ -f $private_world_request ]]; then
    chmod 600 -- "$private_world_request"
    private_world_request_present=1
fi

private_world_snapshot_present=0
if [[ -f $private_world_snapshot ]]; then
    chmod 600 -- "$private_world_snapshot"
    private_world_snapshot_present=1
fi

stop_timeline
stop_backend_capture
stop_route_audit
stop_protection_watch
trap - EXIT INT TERM
snapshot_processes after
snapshot_connections after
finished_at=$(date --iso-8601=seconds)

backend_pcap_bytes=0
if [[ -f $backend_pcap ]]; then
    # Depending on the local tcpdump build, the save file may have been
    # created before privileges were dropped. Normalize ownership narrowly to
    # this capture file so subsequent analysis never needs root.
    sudo chown -- "$(id -u):$(id -g)" "$backend_pcap" 2>/dev/null || true
    backend_pcap_bytes=$(stat -c '%s' -- "$backend_pcap")
    if (( backend_pcap_bytes > 24 )); then
        tcpdump -nn -tttt -q -r "$backend_pcap" \
            > "$output_dir/backend-packets-summary.txt" 2>/dev/null || true
    fi
fi

copied_logs=0
while IFS= read -r -d '' log; do
    cp -- "$log" "$output_dir/"
    copied_logs=$((copied_logs + 1))
done < <(find "$proton_log_dir" -maxdepth 1 -type f -name 'steam-*.log' \
    -newer "$marker" -print0)

copied_protection_logs=0
if [[ $capture_protection == 1 ]]; then
    while IFS= read -r -d '' log; do
        cp -- "$log" "$output_dir/"
        copied_protection_logs=$((copied_protection_logs + 1))
    done < <(find "$proton_log_dir" -maxdepth 1 -type f -name 'sdk-protection-linux-*.log' \
        -newer "$marker" -print0)
fi

probe_log_copied=0
probe_log_bytes=0
probe_log_mode=none
if [[ -f $probe_log ]]; then
    probe_log_finish_size=$(stat -c '%s' -- "$probe_log")
    if (( probe_log_finish_size > probe_log_start_size )); then
        tail -c "+$((probe_log_start_size + 1))" -- "$probe_log" \
            > "$output_dir/project-isac-uplay-probe.log"
        probe_log_bytes=$((probe_log_finish_size - probe_log_start_size))
        probe_log_copied=1
        probe_log_mode=appended-only
    elif (( probe_log_finish_size < probe_log_start_size )); then
        cp -- "$probe_log" "$output_dir/project-isac-uplay-probe.log"
        probe_log_bytes=$probe_log_finish_size
        probe_log_copied=1
        probe_log_mode=full-after-truncate
    fi
fi

local_uplay_log_copied=0
local_uplay_log_bytes=0
local_uplay_log_mode=none
if [[ -f $local_uplay_log ]]; then
    local_uplay_log_finish_size=$(stat -c '%s' -- "$local_uplay_log")
    if (( local_uplay_log_finish_size > local_uplay_log_start_size )); then
        tail -c "+$((local_uplay_log_start_size + 1))" \
            -- "$local_uplay_log" \
            > "$output_dir/project-isac-uplay-local.log"
        local_uplay_log_bytes=$((
            local_uplay_log_finish_size - local_uplay_log_start_size
        ))
        local_uplay_log_copied=1
        local_uplay_log_mode=appended-only
    elif (( local_uplay_log_finish_size < local_uplay_log_start_size )); then
        cp -- "$local_uplay_log" \
            "$output_dir/project-isac-uplay-local.log"
        local_uplay_log_bytes=$local_uplay_log_finish_size
        local_uplay_log_copied=1
        local_uplay_log_mode=full-after-truncate
    fi
fi

stack_probe_log_copied=0
stack_probe_log_bytes=0
stack_probe_log_mode=none
if [[ -f $stack_probe_log ]]; then
    stack_probe_log_finish_size=$(stat -c '%s' -- "$stack_probe_log")
    if (( stack_probe_log_finish_size > stack_probe_log_start_size )); then
        tail -c "+$((stack_probe_log_start_size + 1))" -- "$stack_probe_log" \
            > "$output_dir/project-isac-stack-probe.log"
        stack_probe_log_bytes=$((
            stack_probe_log_finish_size - stack_probe_log_start_size
        ))
        stack_probe_log_copied=1
        stack_probe_log_mode=appended-only
    elif (( stack_probe_log_finish_size < stack_probe_log_start_size )); then
        cp -- "$stack_probe_log" \
            "$output_dir/project-isac-stack-probe.log"
        stack_probe_log_bytes=$stack_probe_log_finish_size
        stack_probe_log_copied=1
        stack_probe_log_mode=full-after-truncate
    fi
fi

code_probe_log_copied=0
code_probe_log_bytes=0
code_probe_log_mode=none
if [[ -f $code_probe_log ]]; then
    code_probe_log_finish_size=$(stat -c '%s' -- "$code_probe_log")
    if (( code_probe_log_finish_size > code_probe_log_start_size )); then
        tail -c "+$((code_probe_log_start_size + 1))" -- "$code_probe_log" \
            > "$output_dir/project-isac-code-probe.log"
        code_probe_log_bytes=$((
            code_probe_log_finish_size - code_probe_log_start_size
        ))
        code_probe_log_copied=1
        code_probe_log_mode=appended-only
    elif (( code_probe_log_finish_size < code_probe_log_start_size )); then
        cp -- "$code_probe_log" \
            "$output_dir/project-isac-code-probe.log"
        code_probe_log_bytes=$code_probe_log_finish_size
        code_probe_log_copied=1
        code_probe_log_mode=full-after-truncate
    fi
fi

dispatch_probe_log_copied=0
dispatch_probe_log_bytes=0
dispatch_probe_log_mode=none
if [[ -f $dispatch_probe_log ]]; then
    dispatch_probe_log_finish_size=$(stat -c '%s' -- "$dispatch_probe_log")
    if (( dispatch_probe_log_finish_size > dispatch_probe_log_start_size )); then
        tail -c "+$((dispatch_probe_log_start_size + 1))" \
            -- "$dispatch_probe_log" \
            > "$output_dir/project-isac-dispatch-probe.log"
        dispatch_probe_log_bytes=$((
            dispatch_probe_log_finish_size - dispatch_probe_log_start_size
        ))
        dispatch_probe_log_copied=1
        dispatch_probe_log_mode=appended-only
    elif (( dispatch_probe_log_finish_size < dispatch_probe_log_start_size )); then
        cp -- "$dispatch_probe_log" \
            "$output_dir/project-isac-dispatch-probe.log"
        dispatch_probe_log_bytes=$dispatch_probe_log_finish_size
        dispatch_probe_log_copied=1
        dispatch_probe_log_mode=full-after-truncate
    fi
fi

plaintext_probe_log_copied=0
plaintext_probe_log_bytes=0
plaintext_probe_log_mode=none
if [[ -f $plaintext_probe_log ]]; then
    plaintext_probe_log_finish_size=$(stat -c '%s' -- "$plaintext_probe_log")
    if (( plaintext_probe_log_finish_size > plaintext_probe_log_start_size )); then
        tail -c "+$((plaintext_probe_log_start_size + 1))" \
            -- "$plaintext_probe_log" \
            > "$output_dir/project-isac-plaintext-probe.log"
        plaintext_probe_log_bytes=$((
            plaintext_probe_log_finish_size - plaintext_probe_log_start_size
        ))
        plaintext_probe_log_copied=1
        plaintext_probe_log_mode=appended-only
    elif (( plaintext_probe_log_finish_size < plaintext_probe_log_start_size )); then
        cp -- "$plaintext_probe_log" \
            "$output_dir/project-isac-plaintext-probe.log"
        plaintext_probe_log_bytes=$plaintext_probe_log_finish_size
        plaintext_probe_log_copied=1
        plaintext_probe_log_mode=full-after-truncate
    fi
fi

uplay_abi_probe_log_copied=0
uplay_abi_probe_log_bytes=0
uplay_abi_probe_log_mode=none
if [[ -f $uplay_abi_probe_log ]]; then
    uplay_abi_probe_log_finish_size=$(stat -c '%s' -- "$uplay_abi_probe_log")
    if (( uplay_abi_probe_log_finish_size > uplay_abi_probe_log_start_size )); then
        tail -c "+$((uplay_abi_probe_log_start_size + 1))" \
            -- "$uplay_abi_probe_log" \
            > "$output_dir/project-isac-uplay-abi-probe.log"
        uplay_abi_probe_log_bytes=$((
            uplay_abi_probe_log_finish_size - uplay_abi_probe_log_start_size
        ))
        uplay_abi_probe_log_copied=1
        uplay_abi_probe_log_mode=appended-only
    elif (( uplay_abi_probe_log_finish_size < uplay_abi_probe_log_start_size )); then
        cp -- "$uplay_abi_probe_log" \
            "$output_dir/project-isac-uplay-abi-probe.log"
        uplay_abi_probe_log_bytes=$uplay_abi_probe_log_finish_size
        uplay_abi_probe_log_copied=1
        uplay_abi_probe_log_mode=full-after-truncate
    fi
fi

{
    echo "Label: $label"
    echo "Started: $started_at"
    echo "Finished: $finished_at"
    echo "Install directory: $install_dir"
    echo "Compatdata directory: ${compatdata_dir:-not supplied}"
    echo "Proton logs copied: $copied_logs"
    echo "Uplay probe log copied: $probe_log_copied"
    echo "Uplay probe log mode: $probe_log_mode"
    echo "Uplay probe bytes captured: $probe_log_bytes"
    echo "Local Uplay log copied: $local_uplay_log_copied"
    echo "Local Uplay log mode: $local_uplay_log_mode"
    echo "Local Uplay bytes captured: $local_uplay_log_bytes"
    echo "Stack probe log copied: $stack_probe_log_copied"
    echo "Stack probe log mode: $stack_probe_log_mode"
    echo "Stack probe bytes captured: $stack_probe_log_bytes"
    echo "Code probe log copied: $code_probe_log_copied"
    echo "Code probe log mode: $code_probe_log_mode"
    echo "Code probe bytes captured: $code_probe_log_bytes"
    echo "Dispatch probe log copied: $dispatch_probe_log_copied"
    echo "Dispatch probe log mode: $dispatch_probe_log_mode"
    echo "Dispatch probe bytes captured: $dispatch_probe_log_bytes"
    echo "Plaintext probe log copied: $plaintext_probe_log_copied"
    echo "Plaintext probe log mode: $plaintext_probe_log_mode"
    echo "Plaintext probe bytes captured: $plaintext_probe_log_bytes"
    echo "Uplay ABI probe log copied: $uplay_abi_probe_log_copied"
    echo "Uplay ABI probe log mode: $uplay_abi_probe_log_mode"
    echo "Uplay ABI probe bytes captured: $uplay_abi_probe_log_bytes"
    echo "Backend packet capture enabled: $capture_backend"
    echo "Backend packet capture filter: $capture_backend_filter"
    echo "Backend packet capture bytes: $backend_pcap_bytes"
    echo "Route audit requested: $capture_routes"
    echo "SDK protection diagnosis requested: $capture_protection"
    echo "Linux protection traces copied: $copied_protection_logs"
    if [[ -f $output_dir/route-audit-summary.txt ]]; then
        echo "Route audit summary: route-audit-summary.txt (sampled prefix-owned endpoints; not exhaustive)"
    elif [[ $capture_routes == 1 ]]; then
        echo "Route audit summary: unavailable; inspect route-audit-errors.log"
    fi
    echo "Action markers enabled: $capture_action_markers"
    if [[ -f $action_markers_file ]]; then
        echo "Action markers recorded: $(( $(wc -l < "$action_markers_file") - 1 ))"
    else
        echo "Action markers recorded: 0"
    fi
    echo "Private type0003 capture existed at start: $private_type3_capture_existed"
    echo "Private type0003 capture present at finish: $private_type3_capture_present"
    echo "Private type0003 capture copied to evidence: 0"
    echo "Private world request existed at start: $private_world_request_existed"
    echo "Private world request present at finish: $private_world_request_present"
    echo "Private world request copied to evidence: 0"
    echo "Private world snapshot existed at start: $private_world_snapshot_existed"
    echo "Private world snapshot present at finish: $private_world_snapshot_present"
    echo "Private world snapshot copied to evidence: 0"
    echo "Kernel: $(uname -srmo)"
    if [[ -r /etc/os-release ]]; then
        awk -F= '$1 == "PRETTY_NAME" { print "Distribution: " $2 }' /etc/os-release
    fi
    if command -v lspci >/dev/null 2>&1; then
        echo "Graphics adapters:"
        lspci -nn | awk 'BEGIN { IGNORECASE=1 } /(vga|3d|display)/ { print }'
    fi
    echo "Network interfaces at finish:"
    ip -brief address 2>/dev/null || true
    if [[ -n $compatdata_dir ]]; then
        echo "Compatdata disk usage: $(du -sh -- "$compatdata_dir" 2>/dev/null | cut -f1)"
    fi
} > "$output_dir/summary.txt"

rm -- "$marker"
echo "Capture complete: $output_dir"
if (( copied_logs == 0 )); then
    echo "WARNING: No new Proton log was found in $proton_log_dir" >&2
    echo "Restart Steam and verify the launch option before retrying." >&2
fi
echo "Review all files, especially the Proton log, before sharing them."
if [[ $capture_backend == 1 ]]; then
    echo "Keep $backend_pcap_name private; it may contain opaque session material."
fi
if (( plaintext_probe_log_copied == 1 )); then
    echo "Keep project-isac-plaintext-probe.log private; gameplay messages may contain identifiers."
fi
if (( private_world_request_present == 1 )); then
    echo "Keep project-isac-world-request-private.bin private; it may contain account or session material."
fi
if (( private_world_snapshot_present == 1 )); then
    echo "Keep project-isac-world-bootstrap-private.bin private; it contains a timed world-session replay stream."
fi
